### ISSUE TITLE
better app icon?

### ISSUE THREAD

**Issue by blizzz** [nextcloud/pdf_converter#5]
I quickly crafted https://github.com/nextcloud/pdf_converter/blob/master/img/app-dark.svg which isn't terribly awesome. Office documents, including various things in plain text, and also images, can be converted to PDF, automagically. I tried to depict it with an arrow pointing towards PDF. At least the arrow's to thin… mayber there are better ideas, too.

may i ask one of @nextcloud/designers ?

**Comment by juliushaertl** [comment]
I think the concept of having an arrow directed towards the filetype icon is fine. Here is a proposal with an arrow that is a bit stronger. 

![convertpdf](https://user-images.githubusercontent.com/3404133/47421115-3a60ac80-d780-11e8-825d-1b4bcc3d7c5a.png)

**Comment by blizzz** [comment]
@juliushaertl nice, thx! do you have this as svg, too?

**Comment by juliushaertl** [comment]
Sure, I'll create a PR.
